# Usamos la imagen oficial que prefieras para AWS
FROM mysql:8.0

# Opcional: Si tuvieras un script init.sql para crear tablas, iría así:
# COPY init.sql /docker-entrypoint-initdb.d/

# Exponemos el puerto
EXPOSE 3306

 
 
