name: CI/CD Frontend

on:
  push:
    branches: [ "deploy" ]
    paths:
      - 'front_despacho/**'

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construir, etiquetar y subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: tienda-frontend
        IMAGE_TAG: latest
      run: |
        cd front_despacho
        # Inyectamos las variables de entorno para que Vite las lea al compilar
        echo "VITE_API_VENTAS_URL=http://54.86.165.16:8080" > .env
        echo "VITE_API_DESPACHOS_URL=http://54.86.165.16:8090" >> .env
        
        # Construimos y subimos la imagen
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar Frontend en EC2 via SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters commands="aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }} ; sudo docker pull ${{ secrets.ECR_REGISTRY }}/tienda-frontend:latest ; sudo docker stop front-container || true ; sudo docker rm front-container || true ; sudo docker run -d --name front-container -p 80:80 ${{ secrets.ECR_REGISTRY }}/tienda-frontend:latest"