name: CI/CD DB

on:
  push:
    branches: [ "deploy" ]
    paths:
      - 'db/**'

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construir, etiquetar y subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: tienda-db
        IMAGE_TAG: latest
      run: |
        cd db
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Desplegar DB en EC2 via SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_DB_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters commands=[ \
            "aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}", \
            "sudo docker pull ${{ secrets.ECR_REGISTRY }}/tienda-db:latest", \
            "sudo docker stop db-container || true", \
            "sudo docker rm db-container || true", \
            "sudo docker run -d --name db-container -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin123 -e MYSQL_DATABASE=db_microservicios ${{ secrets.ECR_REGISTRY }}/tienda-db:latest" \
          ]    